In [11]:
import numpy as np
import sympy as sp

def qr_decomi(R):
    m, n = R.shape
    Q = np.eye(m)
    for i in range(n - (m == n)):
        H = np.eye(m)
        H[i:, i:] = House(R[i:, i])
        Q = Q @ H
        R = H @ R
    return Q, R

def House(A):
    e = np.zeros(A.shape[0])
    e[0] = 1
    if (A[0] < 0):
        norm = -(np.linalg.norm(A) * e[:, None])
    else:
        norm = np.linalg.norm(A) * e[:, None]
    u = A[:, None] + norm
    v = u / np.linalg.norm(u)
    I = np.eye(A.shape[0])
    H = I - ((2 * np.matmul(u, np.transpose(u))) / np.matmul(np.transpose(u), u))
    return H



# A = np.array([[11, 2, -8],
#               [2, 2, 10],
#               [-8, 10, 5]])

# A = np.array([[1, -3, 4],
#               [4, -7, 8],
#               [6, -7, 7]])

# A = np.array([[13, 9, -7],
#               [6, 8, -3],
#               [8, -1, 12]])

A = np.array([[-4, -2, -7, 8],
              [2, 7,  4, 9],
              [2, 0, 6, -3],
              [6, 4, -10, -4]])

# A = np.array([[4, 1, 1, 2, 1], 
#               [1, 2, -1, 1, 1],
#               [3, 1, 1, 1, 1],
#               [2, 1, 1, 4, 1],
#               [2, -1, 1, 1, 5]])

print(A, '\n')

def Find_eiegenValues(A):
    n = A.shape[0]
    k = 0
    itter = 0
    for i in range(n):
        Q, R = qr_decomi(A)
        A = np.dot(R, Q)
        while (np.linalg.det(A - A[i] * np.eye(n)) != 0):
            Q, R = qr_decomi(A)
            A = np.dot(R, Q)
            itter += 1
            if (itter == 1000):
                itter = 0
                break
        k += 1
        if (k == n):
            break
    return A

def Find_ComplexEigenValues(B):
    lambd = sp.symbols('lambd')
    n = B.shape[0]
    I = sp.eye(n)
    equation = sp.det(B - lambd * I)
    B = sp.solve(equation, lambd)
    return B

A = Find_eiegenValues(A)

n = len(A)
eps = 1e-16
flag = 1
Answer = []
for j in range(n - 2, -1, -1):
    B = np.zeros((2, 2))
    k = 0
    a = []
    for i in range(n - 1, -1, -1):
        if (i == j):
            if ((j + 1 + k) != n):
                for i2 in range(i, i + 2):
                    for j2 in range(j, j + 2):
                        B[i2 - i, j2 - j] = A[i2, j2]
            elif (flag == 1):
#                 print(A[i + 1, j + 1])
                Answer.append(A[i + 1][j + 1])
            if ((i == 0) and ((j + 1 + k) == n)):
#                 print(A[i, j])
                Answer.append(A[i][j])
            break                
        if (np.abs(A[i, j]) < eps):
            k += 1
        else:
            a.append(i)
    if (np.abs(B[1, 0]) > eps):
        flag = 0
        B = Find_ComplexEigenValues(B)
#         print(np.diag(np.diag(B)))
        for k in range(len(B)):
            Answer.append(B[k])
    else: 
        flag = 1
Answer = Answer[::-1]
print(Answer)

[[ -4  -2  -7   8]
 [  2   7   4   9]
 [  2   0   6  -3]
 [  6   4 -10  -4]] 

[-12.916776235184942, 11.03978036263004, 3.43849793627738 + 1.29738099271554*I, 3.43849793627738 - 1.29738099271554*I]


In [12]:
w, v = np.linalg.eig(A)

print(w)

[-12.91677624+0.j          11.03978036+0.j
   3.43849794+1.29738099j   3.43849794-1.29738099j]
